[package]
name = "minecraft-gooning-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.6.1"
rand = "0.9.1"
dotenv = "0.15.0"
anyhow = "1.0.68"
minecraft-client-rs = "0.1.3"
